swagger: '2.0'
basePath: /api
info:
  version: 10.1.0
  title: Redash SDK
  description: |
    This is a simple SDK for programmatic management of Redash. For more information, see github.com/recolabs/redash-go-sdk. We created this client based on the python code of version 10.1.0 of redash - https://github.com/getredash/redash
  contact:
    name: recolabs.ai
    email: rnd@recolabs.ai
    url: https://www.recolabs.ai
securityDefinitions:
  key:
    type: apiKey
    in: header
    name: user-api-key
security:
- key: []
schemes:
- https
- http
x-schemes:
- unix
paths:
  /data_sources:
    get:
      consumes:
      - application/x-www-form-urlencoded
      tags: [DataSources]
      operationId: list
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/dataSource'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    post:
      tags: [DataSources]
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            options:
              type: object
            type:
              type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/dataSource'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /data_sources/{id}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      tags: [DataSources]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '200':
          description: Get data source by ID
          schema:
            $ref: '#/definitions/dataSource'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    delete:
      consumes:
      - application/x-www-form-urlencoded
      tags: [DataSources]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '204':
          description: Data Source was deleted
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /visualizations:
    post:
      tags: [Visualizations]
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            options:
              type: object
            type:
              type: string
            query_id:
              type: integer
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/visualization'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /visualizations/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      tags: [Visualizations]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '200':
          description: Visualization was deleted
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /queries:
    get:
      consumes:
      - application/x-www-form-urlencoded
      tags: [Queries]
      parameters:
      - in: query
        name: page_size
        type: integer
        default: 100
        description: Numeric ID to limit number of results
      responses:
        '200':
          description: List queries
          schema:
            $ref: '#/definitions/queryList'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    post:
      tags: [Queries]
      consumes:
      - application/json
      parameters:
      - name: body
        in: body
        schema:
          type: object
          required:
          - is_draft
          properties:
            data_source_id:
              type: integer
              format: int64
            options:
              type: object
            query:
              type: string
            name:
              type: string
            version:
              type: integer
              format: int64
            is_draft:
              type: boolean
            description:
              type: string
            schedule:
              $ref: '#/definitions/schedule'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/query'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /queries/{id}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      tags: [Queries]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '200':
          description: Returned query object
          schema:
            $ref: '#/definitions/query'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    post:
      consumes:
      - application/json
      tags: [Queries]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      - name: body
        in: body
        schema:
          type: object
          required:
          - is_draft
          properties:
            id:
              type: integer
              format: int64
            is_draft:
              type: boolean
            version:
              type: integer
              format: int64
              default: 1
      responses:
        '200':
          description: Returned query object
          schema:
            $ref: '#/definitions/query'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    delete:
      consumes:
      - application/x-www-form-urlencoded
      tags: [Queries]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '200':
          description: Query is archived
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /queries/{id}/results:
    post:
      consumes:
      - application/json
      tags: [Queries]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      - name: body
        in: body
        schema:
          type: object
          required:
          - id
          - max_age
          - apply_auto_limit
          - parametersDict
          properties:
            id:
              type: integer
              format: int64
            max_age:
              type: integer
              format: int64
            apply_auto_limit:
              type: boolean
            parameters:
              type: object
              minLength: 2
      responses:
        '200':
          description: Query is executed
          schema:
            $ref: '#/definitions/jobResult'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
    get:
      consumes:
      - application/x-www-form-urlencoded
      tags: [Queries]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '200':
          description: Query is executed
          schema:
            $ref: '#/definitions/queryResult'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /queries/{id}/regenerate_api_key:
    post:
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      consumes:
      - application/x-www-form-urlencoded
      tags: [Queries]
      responses:
        '200':
          description: The query which token was refreshed
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /users/{id}:
    get:
      consumes:
      - application/x-www-form-urlencoded
      tags: [Users]
      parameters:
      - in: path
        name: id
        type: integer
        required: true
      responses:
        '200':
          description: Get user by ID
          schema:
            $ref: '#/definitions/user'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
  /ping:
    get:
      tags: [Administration]
      responses:
        '200':
          description: OK
          schema:
            type: string
            example: PONG.
definitions:
  dataSource:
    type: object
    required:
    - name
    - options
    - type
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
      options:
        type: object
        minLength: 2
      type:
        type: string
        enum:
        - aws_es
        - athena
        - azure_kusto
        - bigquery_gce
        - Cassandra
        - scylla
        - clickhouse
        - cloudwatch_insights
        - corporate_memory
        - databricks
        - db2
        - dgraph
        - dynamodb_sql
        - google_analytics
        - google_spreadsheets
        - hive
        - hive_http
        - impala
        - influxdb
        - memsql
        - mssql
        - mssql_odbc
        - rds_mysql
        - oracle
        - pg
        - redshift
        - redshift_iam
        - cockroach
        - phoenix
        - presto
        - qubole
        - rockset
        - insecure_script
        - sparql_endpoint
        - sqlite
        - treasuredata
        - trino
        - yandex_metrika
        - yandex_appmetrika
      syntax:
        type: string
        minLength: 1
  visualization:
    type: object
    required:
    - name
    - options
    - type
    - query_id
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      options:
        type: object
        minLength: 2
      type:
        type: string
        enum:
        - BOXPLOT
        - CHART
        - CHOROPLETH
        - COHORT
        - COUNTER
        - DETAILS
        - FUNNEL
        - MAP
        - PIVOT
        - SANKEY
        - SUNBURST_SEQUENCE
        - TABLE
        - WORD_CLOUD
      query_id:
        type: integer
        minLength: 1
      is_draft:
        type: boolean
  query:
    type: object
    required:
    - name
    - query
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      data_source_id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
      options:
        type: object
        minLength: 2
      query:
        type: string
        minLength: 1
      is_draft:
        type: boolean
      version:
        type: integer
        format: int64
        default: 1
      latest_query_data_id:
        type: integer
        format: int64
        default: 1
      schedule:
        $ref: '#/definitions/schedule'
      visualizations:
        type: array
        items:
          $ref: '#/definitions/visualization'
  queryList:
    type: object
    properties:
      count:
        type: integer
        format: int64
        readOnly: true
      page:
        type: integer
        format: int64
        readOnly: true
      results:
        type: array
        items:
          $ref: '#/definitions/query'
  user:
    type: object
    required:
    - name
    - email
    - orgName
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
      email:
        type: string
        format: email
      orgName:
        type: string
      groups:
        type: array
        items:
          type: integer
          format: int64
      apiKey:
        type: string
      created_at:
        type: string
        format: date-time
      updated_at:
        type: string
        format: date-time
  error:
    type: object
    required:
    - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
  queryResult:
    type: object
    properties:
      query_result:
        type: object
        properties:
          id:
            type: integer
            format: int64
          query_hash:
            type: string
          query:
            type: string
          data:
            type: object
            properties:
              columns:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    friendly_name:
                      type: string
                    type:
                      type: string
              rows:
                type: array
                items:
                  type: object
                  additionalProperties: {}
              metadata:
                type: object
                properties:
                  data_scanned:
                    type: integer
                    format: int64
                  athena_query_id:
                    type: string
          data_source_id:
            type: integer
            format: int64
          retrieved_at:
            type: string
            format: date-time
  jobResult:
    type: object
    properties:
      job:
        type: object
        properties:
          id:
            type: string
          updated_at:
            type: integer
            format: int32
          status:
            type: integer
            format: int32
          error:
            type: string
          result:
            type: string
            format: nullable
          query_result_id:
            type: string
            format: nullable
  schedule:
    properties:
      interval:
        type: integer
        format: int64
      until:
        type: string
      day_of_week:
        type: string
      time:
        type: string
