name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lintest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Download latest earthly
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.6.4/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly'"
    
    - name: Earthly version
      run: earthly --version
    
    - name: Run lintest
      run: earthly --strict +lintest  # Can't use --ci because we want output

    - name: Check Earthly local output
      run: ls -la .

    - uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
        verbose: true

